<a href="https://colab.research.google.com/github/manavbansal1/google-collab/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy Practice

In [1]:
import numpy as np

In [11]:
numpy_array = np.array([(1,2,3,4,5), (6,7,8,9,10)], dtype='int') # dtype is optional

In [14]:
print(numpy_array)
print(numpy_array.shape) # for 2d array no. of rows * no. of columns
print(type(numpy_array))
print(numpy_array.size) # total nuber of elements


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)
<class 'numpy.ndarray'>
10


In [15]:
c = np.array([1,2,3,4,5,6,7,8,9], dtype='float')
print(c)
print(type(c))

[1. 2. 3. 4. 5. 6. 7. 8. 9.]
<class 'numpy.ndarray'>


Initial Placeholers in numpy array

In [21]:
x = np.zeros((4,5), dtype='bool') #dtype can be int float str or bool
print(x)

[[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]


In [22]:
# numpy arrays of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [24]:
# array of a specific numbers
z = np.full((5,4), 5,  dtype='float')
print(z)

[[5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]]


In [26]:
# create an identity matrix
a = np.eye(4, dtype='int')
print(a)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [29]:
# create a numpy array with random arrays

b = np.random.random((3,4))
print(b)

[[0.15698912 0.21035696 0.62359532 0.78779139]
 [0.2892467  0.98811078 0.46126413 0.27034145]
 [0.85140945 0.92014756 0.56627464 0.32836962]]


In [32]:
# Create a matrix between 10 and 100 ints
c = np.random.randint(10,100,(3,5))
print(c)

[[93 40 11 53 71]
 [57 46 75 30 28]
 [35 32 96 72 92]]


In [35]:
# array of 5 evenly spaced values between 10 and 30
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [36]:
# array of evenly spaced values --> specifying the step not the number of values we need
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [37]:
# list to numpy array
list1= [1,2,3,4,5,6,7]
np_array = np.asanyarray(list1)
print(np_array)
print(type(np_array))

[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>


Analyzing the np arrays

In [38]:
c = np.random.randint(10,90,(5,5))
print(c)

[[45 15 69 76 51]
 [72 59 56 76 67]
 [71 42 79 23 30]
 [11 62 70 31 78]
 [68 14 75 80 31]]


In [42]:
# array dimension
print(c.shape) # n*m matrix

# num of dimesnions
print(c.ndim)

# total number of elemnets in the array
print(c.size)

# checking the data type of the values in array
print(c.dtype)


(5, 5)
2
25
int64


Mathematical operation on a numpy array

In [47]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2) # normal list concatinate

a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[[6 2 1]
 [8 7 3]
 [4 9 2]]
[[11 17 14]
 [17 15 12]
 [16 17 16]]


In [50]:
print(a + b) # element wise addition when its np array

[[17 19 15]
 [25 22 15]
 [20 26 18]]


In [53]:
print(a - b) # element wise subtraction when its np array
print(a * b) # element wise multiplication when its np array
print(a / b) # element wise division when its np array

[[ -5 -15 -13]
 [ -9  -8  -9]
 [-12  -8 -14]]
[[ 66  34  14]
 [136 105  36]
 [ 64 153  32]]
[[0.54545455 0.11764706 0.07142857]
 [0.47058824 0.46666667 0.25      ]
 [0.25       0.52941176 0.125     ]]


In [57]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print("array A = ", a)
print("array B = ", b)
print ("---------------")
print(np.add(a, b))
print ("---------------")
print (np.subtract(a,b))
print ("---------------")
print (np.multiply(a,b))
print ("---------------")
print (np.divide(a,b))

array A =  [[8 3 3]
 [5 0 9]
 [0 0 8]]
array B =  [[13 11 17]
 [19 15 14]
 [12 11 12]]
---------------
[[21 14 20]
 [24 15 23]
 [12 11 20]]
---------------
[[ -5  -8 -14]
 [-14 -15  -5]
 [-12 -11  -4]]
---------------
[[104  33  51]
 [ 95   0 126]
 [  0   0  96]]
---------------
[[0.61538462 0.27272727 0.17647059]
 [0.26315789 0.         0.64285714]
 [0.         0.         0.66666667]]


Array Manipulation

In [61]:
array = np.random.randint(0,10,(2,3))
print(array)
print (array.shape)

# transpose
trans = np.transpose(array)
print(trans)
print (trans.shape)


[[6 4 0]
 [6 5 3]]
(2, 3)
[[6 6]
 [4 5]
 [0 3]]
(3, 2)


In [63]:
# Another method for transpose

trans2 = array.T
print(trans2)
print (trans2.shape)

[[6 6]
 [4 5]
 [0 3]]
(3, 2)


In [66]:
# reshaping an array
a= np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

b = a.reshape(3,2)
print(b)
print(b.shape)

[[7 2 8]
 [4 9 8]]
(2, 3)
[[7 2]
 [8 4]
 [9 8]]
(3, 2)
