<a href="https://colab.research.google.com/github/manavbansal1/google-collab/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy Practice

In [1]:
import numpy as np

In [11]:
numpy_array = np.array([(1,2,3,4,5), (6,7,8,9,10)], dtype='int') # dtype is optional

In [14]:
print(numpy_array)
print(numpy_array.shape) # for 2d array no. of rows * no. of columns
print(type(numpy_array))
print(numpy_array.size) # total nuber of elements


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)
<class 'numpy.ndarray'>
10


In [15]:
c = np.array([1,2,3,4,5,6,7,8,9], dtype='float')
print(c)
print(type(c))

[1. 2. 3. 4. 5. 6. 7. 8. 9.]
<class 'numpy.ndarray'>


Initial Placeholers in numpy array

In [21]:
x = np.zeros((4,5), dtype='bool') #dtype can be int float str or bool
print(x)

[[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]


In [22]:
# numpy arrays of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [24]:
# array of a specific numbers
z = np.full((5,4), 5,  dtype='float')
print(z)

[[5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]]


In [26]:
# create an identity matrix
a = np.eye(4, dtype='int')
print(a)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [29]:
# create a numpy array with random arrays

b = np.random.random((3,4))
print(b)

[[0.15698912 0.21035696 0.62359532 0.78779139]
 [0.2892467  0.98811078 0.46126413 0.27034145]
 [0.85140945 0.92014756 0.56627464 0.32836962]]


In [32]:
# Create a matrix between 10 and 100 ints
c = np.random.randint(10,100,(3,5))
print(c)

[[93 40 11 53 71]
 [57 46 75 30 28]
 [35 32 96 72 92]]


In [35]:
# array of 5 evenly spaced values between 10 and 30
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [36]:
# array of evenly spaced values --> specifying the step not the number of values we need
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [37]:
# list to numpy array
list1= [1,2,3,4,5,6,7]
np_array = np.asanyarray(list1)
print(np_array)
print(type(np_array))

[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>
